# Set terminal to preserve vim colours
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Reload tmux config
bind r source-file ~/.tmux.conf

# Set vim-like bindings for navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Vim-like splitting of the windows
bind-key s split-window -v -c '#{pane_current_path}'
bind-key v split-window -h -c '#{pane_current_path}'

# Vim inspired copy and paste
# enter copy mode with CTRL-b [
setw -g mode-keys vi
bind P paste-buffer

# Enlarge scroll history
set -g history-limit 10000

# Set location of status bar
set -g status-position top
#set -g status-position bottom

# Change appearance of status bar
set -g status-style 'fg=black,bg=white'

# Status left
set -g status-left-length 60
set -g status-left "#[fg=#c5af78]Session: #S "

# Set colours for active window
set -g window-status-current-style 'fg=red,bg=white'

# Start windows and panes at 1 and not 0
set -g base-index 1
setw -g pane-base-index 1

# Allows for faster key repetition
set -s escape-time 10

# Turn on the mouse for scrolling etc.
set -g mouse on
